[2023-10-03T08:44:49.485+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: launches_getter.get_todays_launches manual__2023-10-03T08:39:08.987927+00:00 [queued]>
[2023-10-03T08:44:49.494+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: launches_getter.get_todays_launches manual__2023-10-03T08:39:08.987927+00:00 [queued]>
[2023-10-03T08:44:49.494+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-10-03T08:44:49.513+0000] {taskinstance.py:1350} INFO - Executing <Task(SimpleHttpOperator): get_todays_launches> on 2023-10-03 08:39:08.987927+00:00
[2023-10-03T08:44:49.518+0000] {standard_task_runner.py:57} INFO - Started process 1413 to run task
[2023-10-03T08:44:49.520+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'launches_getter', 'get_todays_launches', 'manual__2023-10-03T08:39:08.987927+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/launches.py', '--cfg-path', '/tmp/tmpzh03bwrp']
[2023-10-03T08:44:49.521+0000] {standard_task_runner.py:85} INFO - Job 108: Subtask get_todays_launches
[2023-10-03T08:44:49.560+0000] {task_command.py:410} INFO - Running <TaskInstance: launches_getter.get_todays_launches manual__2023-10-03T08:39:08.987927+00:00 [running]> on host f21dc12153d8
[2023-10-03T08:44:49.635+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='launches_getter' AIRFLOW_CTX_TASK_ID='get_todays_launches' AIRFLOW_CTX_EXECUTION_DATE='2023-10-03T08:39:08.987927+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-03T08:39:08.987927+00:00'
[2023-10-03T08:44:49.636+0000] {http.py:123} INFO - Calling HTTP method
[2023-10-03T08:44:49.643+0000] {base.py:73} INFO - Using connection ID 'thespacedevs_dev' for task execution.
[2023-10-03T08:44:49.895+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 130, in execute
    if not self.response_check(response, **kwargs):
  File "/opt/airflow/dags/launches.py", line 33, in <lambda>
    response_check=lambda response: response.text["count"] > 0,
TypeError: string indices must be integers
[2023-10-03T08:44:49.904+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=launches_getter, task_id=get_todays_launches, execution_date=20231003T083908, start_date=20231003T084449, end_date=20231003T084449
[2023-10-03T08:44:49.924+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 108 for task get_todays_launches (string indices must be integers; 1413)
[2023-10-03T08:44:49.933+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T08:44:49.953+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
